### ISSUE TITLE
Broken :(

### ISSUE THREAD

**Issue by Ten0** [Asthowen/AlphacodersWallpaperDownloader#1]
[The example command](https://github.com/Asthowen/AlphacodersDownloader#examples) gives:
```
⠋ Recovery of the URLS of all the wallpapers...
'NoneType' object has no attribute 'find_all'
```

The joys of scrapers I guess ^^'

**Comment by Ten0** [comment]
That appears to be because we get a 403 at https://github.com/Asthowen/AlphacodersDownloader/blob/6a0c85f7bad1641a27c87bc0a33d4e92e74cbc9f/alphacoders_downloader/alphacoders_downloader.py#L55

And that appears to be because of Cloudflare. Smells bad :(

**Comment by Ten0** [comment]
Got it to work by pasting the entire pre-loaded body of the non-mobile version (via auto loading and scrolling manually) into a local file and using that as body, and commenting out this:
https://github.com/Asthowen/AlphacodersDownloader/blob/6a0c85f7bad1641a27c87bc0a33d4e92e74cbc9f/alphacoders_downloader/alphacoders_downloader.py#L77-L93

So it seems that Cloudflare won't let us download the page, but it will let us download the actual images.

**Comment by Asthowen** [comment]
Hello, thank you for reporting the problem!

I started to look at it and indeed it's an annoying problem... I won't have time to look into it for two weeks ^^', if you have time you can open a PR.

**Comment by mingzhang96** [comment]
unfortunately it is still not working

**Comment by Ten0** [comment]
Since the issue is still open and that was only 3 weeks ago one may indeed assume that. Please avoid sending such messages as that notifies people for nothing.

**Comment by Asthowen** [comment]
Hello @Ten0! 

First of all, sorry for the wait (I've been quite busy), indeed I didn't manage to bypass the CloudFlare anti-bot page, so I applied the method you proposed. Even if it's a bit less convenient than before, at least it's functional. I have modified the README to explain the new way of working of the script, if you can test it and tell me again if it works well for you.

Have a nice day (or evening)

**Comment by Ten0** [comment]
That's really cool!
No worries for the wait, I had managed to download my new set of background screens using the workaround when I reported this issue so I definitely wasn't in a hurry ;)
